// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgvssvntkwepldcmrjpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndnNzdm50a3dlcGxkY21yanBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTY0NjgsImV4cCI6MjA2Nzg5MjQ2OH0.4D6UWOF6M7zyuleXmzDhF9PBgieWmxjaBSgLFhuD90o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});